Vagrant.configure("2") do |config|

  config.vm.define :nodo1 do |nodo1|
    nodo1.vm.box = "debian/bookworm64"
    nodo1.vm.hostname = "nodo1"
    nodo1.vm.synced_folder ".", "/vagrant", disabled: true

    #Direccionamiento dinámico
    nodo1.vm.network :private_network,
      :type => "dhcp",
      :libvirt__network_name => 'red_vagrant',
      :libvirt__network_address => '192.168.200.0',
      :libvirt__netmask => '255.255.255.0'
      :libvirt__host_ip => '192.168.200.1',
      :libvirt__dhcp_start => '192.168.200.2',
      :libvirt__dhcp_stop => '192.168.200.254',
      use_dhcp_assigned_default_route: true

    #Direccionamiento estático
    nodo1.vm.network :private_network,
      :libvirt__network_name => "red_vagrant_static",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.1",
      :libvirt__forward_mode => "none"
  end

  config.vm.define :nodo2 do |nodo2|
    nodo2.vm.box = "generic/ubuntu2204"
    nodo2.vm.hostname = "nodo2"
    nodo2.vm.synced_folder ".", "/vagrant", disabled: true


    nodo2.vm.network :private_network,
      :libvirt__network_name => "red_vagrant_static",
      :libvirt__dhcp_enabled => false,
      :ip => "10.0.0.2",
      :libvirt__forward_mode => "none"

    nodo2.vm.network :public_network,
      :dev => "br0",
      :mode => "bridge",
      :type => "bridge"

    nodo2.vm.provider :libvirt do |libvirt|
        libvirt.storage :file, size: '1G'
        libvirt.storage :file, size: '1G'
  end
end
end
